server:
  port: 18083
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: ${KEYCLOAK_AUTHORIZATION_GRANT_TYPE}
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI}
client-application:
  resource-server:
    endpoint: ${RESOURCE_SERVER_ENDPOINT}
